import type { CueSheet } from "./cuesheet.ts";
import { type CueFormatId, formats, inputFormatIds } from "./formats.ts";

/**
 * Parses a cue sheet with the given format.
 *
 * @param content Serialized content of the cue sheet.
 * @param formatId ID of the input format.
 * @returns Parsed cue sheet or `undefined` if the given format has no parser.
 */
export function parseCueSheet(
  content: string,
  formatId: CueFormatId,
): CueSheet | undefined {
  return formats[formatId].parse?.(content);
}

/** Result of a cue sheet format detection. */
export interface DetectionResult {
  /** Parsed cue sheet. */
  cueSheet: CueSheet;
  /** ID of the detected format which was successfully parsed. */
  formatId: CueFormatId;
}

/**
 * Detects the format of the given cue sheet and parses it.
 *
 * Tries to parse the serialized content with all supported input formats.
 * Exits as soon as a parser was successful and returned a non-empty cue sheet.
 *
 * @param content Serialized content of the cue sheet.
 * @returns Parsed cue sheet and its format ID or `undefined` if detection failed.
 */
export function detectFormatAndParseCueSheet(
  content: string,
): DetectionResult | undefined {
  let cueSheet: CueSheet | undefined;
  for (const formatId of inputFormatIds) {
    try {
      cueSheet = parseCueSheet(content, formatId);
      if (cueSheet?.cues.length) {
        return { cueSheet, formatId };
      }
    } catch {
      continue;
    }
  }
}

/**
 * Serializes a cue sheet into the given format.
 *
 * If no cue sheet formatter exists, a cue sheet will be generated by joining
 * the individual formatted cues together with newlines.
 *
 * @param cueSheet Cue sheet object.
 * @param formatId ID of the output format.
 * @returns Serialized cue sheet or `undefined` if the given format has neither
 * a cue sheet nor a cue formatter.
 */
export function formatCueSheet(
  cueSheet: CueSheet,
  formatId: CueFormatId,
): string | undefined {
  const { format, formatCue } = formats[formatId];
  if (format) {
    return format(cueSheet);
  } else if (formatCue) {
    return cueSheet.cues.map(formatCue).join("\n");
  } else {
    return undefined;
  }
}
