export interface Cue {
  position: number;
  title: string;
  timeOffset: number;
  performer?: string;
  duration?: number;
}

export type CueFormatter = (cue: Cue) => string;

export interface CueSheet {
  cues: Cue[];
  title?: string;
  performer?: string;
  mediaFile?: string;
  duration?: number;
}

export type CueSheetFormatter = (cueSheet: CueSheet) => string;

export type CueSheetParser = (input: string) => CueSheet;

/** Specification of a cue format. */
export interface CueFormat {
  /** Descriptive name of the format. */
  name: string;
  /** Formatter for a single cue. */
  formatCue?: CueFormatter;
  /**
   * Formatter for a full cue sheet.
   *
   * If no cue sheet formatter is specified, a cue sheet may be generated by
   * joining the individual formatted cues together with newlines.
   */
  format?: CueSheetFormatter;
  /** Parser which extracts a cue sheet. */
  parse?: CueSheetParser;
}
